# Generated by Django 5.2.15 on 2026-07-31 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAutomation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bot_token', models.CharField(max_length=300)),
                ('chat_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('events', models.JSONField(blank=True, default=dict, help_text="Event subscriptions config, e.g. {'issue_created': True, 'issue_updated': True, 'comment_added': True}")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
                ('workspace_integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_automations', to='db.workspaceintegration')),
            ],
            options={
                'verbose_name': 'Telegram Automation',
                'verbose_name_plural': 'Telegram Automations',
                'db_table': 'telegram_automations',
                'ordering': ('-created_at',),
            },
        ),
    ]
