# Generated by Django 5.2.15 on 2026-08-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_slackautomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackautomation',
            name='app_token',
            field=models.CharField(blank=True, help_text='Slack App-Level Token (xapp-...). Get from Basic Information > App-Level Tokens.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slackautomation',
            name='bot_token',
            field=models.CharField(blank=True, help_text='Slack Bot User OAuth Token (xoxb-...). Get from OAuth & Permissions page.', max_length=500, null=True),
        ),
    ]
